### ISSUE TITLE
Support for keystone v3 api

### ISSUE THREAD

**Issue by kisahm** [Juniper/contrail-charms#1]
does anybody tried to deploy the contrail charms with newton keystone v3 api?
we get an authentication problem between contrail and openstack after changing keystone api v2.0 to v3

**Comment by Andrey-mp** [comment]
What version of Contrail are you use?

**Comment by kisahm** [comment]
juniper contrail 4.0

**Comment by Andrey-mp** [comment]
What build?

**Comment by Andrey-mp** [comment]
Are you deploying with these charms?

**Comment by kisahm** [comment]
Build 20 for Xenial
yes we've used this charms

**Comment by kisahm** [comment]
deployed with juju 2.2

**Comment by Andrey-mp** [comment]
Thank you for the issue. I'll check this.
Could you file a bug with detailed error on the launchpad - https://bugs.launchpad.net/juniperopenstack/
And get me a link or assign it to me (apavlov-e)

**Comment by Andrey-mp** [comment]
I filed a bug in the launchpad but it's private. leave here a link just for tracking - https://bugs.launchpad.net/juniperopenstack/+bug/1706422

**Comment by kisahm** [comment]
Could you reproduce the problem?
Can you assign me (username: kisahm)the the launchpad bug?

**Comment by kisahm** [comment]
do you know if contrail RBAC works with keystone api v3 only?

**Comment by Andrey-mp** [comment]
Hi,
Yes, I can reproduce it.
I made the bug public - you can assign it by yourself.
As I know RBAC works with both versions.

**Comment by Andrey-mp** [comment]
Hi,
Issue in the Juniper's LP was closed and new internal build was build.
