### ISSUE TITLE
ContrailPlugin.ini missing RBAC settings

### ISSUE THREAD

**Issue by bbcmicrocomputer** [Juniper/contrail-charms#10]
Deploying Contrail 4.1 using master branch charms with the attached bundle - 
[contrail-docker-bundle-ha-ocata.yaml.txt](https://github.com/Juniper/contrail-charms/files/1793322/contrail-docker-bundle-ha-ocata.yaml.txt).

It appears /etc/neutron/plugins/opencontrail/ContrailPlugin.ini on neutron-api is missing 'aaa_mode' and 'cloud_admin_role' configuration values, as shown in the dump below:
```
###############################################################################
# [ WARNING ]
# Configuration file maintained by Juju. Local changes may be overwritten.
###############################################################################

[APISERVER]
api_server_ip = 192.168.122.34
api_server_port = 8082
multi_tenancy = True

[keystone_authtoken]
auth_host = 192.168.122.241
auth_port = 5000
auth_protocol = http
admin_user = admin
admin_password = password
admin_tenant_name = admin
insecure = True
region_name = RegionOne
```
I haven't been able to prove that RBAC isn't functioning without these settings, but they were required in Contrail 3.2 and it's suggested they're still required according to https://www.juniper.net/documentation/en_US/contrail4.1/topics/concept/role-resource-access-control-vmc.html#jd0e274 .

**Comment by Andrey-mp** [comment]
Hi Robert,

Here is another doc about RBAC (mostly the same) - https://github.com/Juniper/contrail-controller/wiki/RBAC that I used.

And both docs don't have exact instructions for ContrailPlugin.ini settings.
As I know for neutron - api-paste.ini has to be modified and some contrail configs

I tested RBAC with these settings and it worked fine for me.
