### ISSUE TITLE
IP address is never returned

### ISSUE THREAD

**Issue by n-pochet** [Juniper/contrail-charms#115]
Introduced by commit 658deda1f51a211b94632f40aa593390184a03a0, the `ip` variable is never returned.
That causes the contrail-controller to set its `private-address` to a wrong value.

**Comment by n-pochet** [comment]
Using flake8 would easily spot such behavior as it would raise the following error:
`local variable 'ip' is assigned to but never usedflake8(F841)`

**Comment by n-pochet** [comment]
@Andrey-mp Could you please push the new version including this commit to the charmstore?

**Comment by Andrey-mp** [comment]
done
