### ISSUE TITLE
Only the contrail-keystone-auth leader unit publishes auth-info

### ISSUE THREAD

**Issue by aieri** [Juniper/contrail-charms#119]
While performing a new installation of contrail, I have found the contrail-controllers blocked with the following error: `Missing auth info in relation with contrail-auth.`

Looking at relation data between contrail-controller and contrail-keystone-auth, I have found that the auth-info key is only published by the contrail-keystone-auth leader unit, while controllers were expecting to receive it from other units as well.

Manual workaround:

1. grab the auth-info value from the leader unit:
`juju run -u contrail-controller/1 -- relation-get -r <rel-id> - contrail-keystone-auth/<leader>`
1. publish auth-info on non-leader units:
`juju run -u contrail-keystone-auth/<non-leader> -- relation-set -r <rel-id> auth-info='[...]'`

**Comment by Andrey-mp** [comment]
Hi Andrea,
Yes, I've got this logical issue. non-leader units doesn't set any info into relation but contrail-controller reads info from all units and can fail.

In general I supposed that only one contrail-keystone-auth unit will be present in deployment. It just a proxy unit that can be in non-HA mode.
But I'll fix this issue some time later.

**Comment by Andrey-mp** [comment]
https://github.com/Juniper/contrail-charms/commit/e3f045942b75c4b9a00b78a6914da057a3f26c37
