### ISSUE TITLE
Docker container logs are not rotated

### ISSUE THREAD

**Issue by aieri** [Juniper/contrail-charms#124]
No log rotation appears to be configured for the contrail containers (`/var/lib/docker/containers/*/*`).
This causes logs to grow unbounded, which will eventually consume all disk space available on the hosting machines.
The charms should configure native docker log rotation and offer configuration parameters to allow operators to tune retention.

**Comment by Andrey-mp** [comment]
based on this topic https://docs.docker.com/config/containers/logging/json-file/
I would suggest to add two options with the following defaults to each charm with docker:
log-driver: json-file
log-opt: "max-size=20m max-file=5"

log-opt contains space-separated options that should be passed for --log-opt each.

**Comment by Andrey-mp** [comment]
implemented. https://github.com/Juniper/contrail-charms/commit/cae9ecc8438d68df1d2e75b440cd9dbf9fdeadf5
published to charmstore.
