### ISSUE TITLE
Race between check_contrail_status* and the update-status hook

### ISSUE THREAD

**Issue by aieri** [Juniper/contrail-charms#125]
Both the deployed nrpe check and the update-status charm hook run the contrail-status command.
Since contrail-status actually spins up a docker container with a known name ("contrail-status"), and docker container names must be unique, running both the nrpe check and the update-status hook at the same time is not possible.
Since it is not possible to ensure (in general) non overlapping periods for the nrpe check and the update-status hook, race conditions will occur, causing random CRITICAL alerts in nagios.

Possible solutions:
* re-engineer the nrpe check, or the hook, or both to only look at a cached result. Add a cronjob to periodically update the cached result
* modify the contrail-status command to choose a random container name every time it is started

**Comment by Andrey-mp** [comment]
looks like it's only nrpe race. update-hook already set different names in different charms.
but in nrpe I made a mistake and all nrpe checks use same name...

Can you please tell me if I'm wrong?

**Comment by Andrey-mp** [comment]
i fixed nrpe checks.

**Comment by danackerson** [comment]
@Andrey-mp thx for the update. Do you know in which version this fix will be released?

**Comment by Andrey-mp** [comment]
@danackerson i've pushed new version with fix yesterday.
