### ISSUE TITLE
Create VM failed in vrouter-port-control

### ISSUE THREAD

**Issue by AshleyLai** [Juniper/contrail-charms#126]
After the openstack deployed, creation of VM failed with the following error:

2019-11-05 16:43:01.430 128734 ERROR nova.scheduler.utils
[req-a8539374-9b48-4f84-a1c0-c2578f713dd3
7c759021dd1f4c2a888f0a5e7baf91e7 3bf95352cade44dba458aa4a22942926 -
2fe8fbf887f842389ec5e0b0e8eebbdc 2fe8fbf887f842389ec5e0b0e8eebbdc]
[instance: 3d97e13a-b397-4568-a1f4-2301bfc97018] Error from last host:
baubas (node baubas.playground.solutionsqa): [u'Traceback (most recent
call last):\n', u'  File
"/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1863,
in _do_build_and_run_instance\n    filter_properties,
request_spec)\n', u'  File
"/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 2143,
in _build_and_run_instance\n    instance_uuid=instance.uuid,
reason=six.text_type(e))\n', u"RescheduledException: Build of instance
3d97e13a-b397-4568-a1f4-2301bfc97018 was re-scheduled: Failure running
os_vif plugin plug method: Failed to plug VIF
VIFVHostUser(active=True,address=02:f8:92:f6:d9:af,has_traffic_filtering=False,id=f892f6d9-af8f-4ddb-a74b-80f81b92df96,mode='server',network=Network(895d70f3-c924-471e-a980-16953d31257b),path='/var/run/vrouter/uvh_vif_tapf892f6d9-af',plugin='contrail_vrouter',port_profile=<?>,preserve_on_delete=False,vif_name='tapf892f6d9-af').
Got error: Error during the call to vrouter-port-control:
('vrouter-port-control', '--oper=add',
u'--uuid=f892f6d9-af8f-4ddb-a74b-80f81b92df96',
u'--instance_uuid=3d97e13a-b397-4568-a1f4-2301bfc97018',
u'--vn_uuid=895d70f3-c924-471e-a980-16953d31257b',
u'--vm_project_uuid=3bf95352cade44dba458aa4a22942926',
'--ip_address=172.16.0.3', '--ipv6_address=None',
u'--vm_name=instance-0000000d', u'--mac=02:f8:92:f6:d9:af',
u'--tap_name=tapf892f6d9-af', '--port_type=NovaVMPort',
'--vif_type=VhostUser',
u'--vhostuser_socket=/var/run/vrouter/uvh_vif_tapf892f6d9-af',
'--vhostuser_mode=1', '--tx_vlan_id=-1', '--rx_vlan_id=-1')\n"]

**Comment by Andrey-mp** [comment]
@AshleyLai this is not charm error.
this error is caused by different host name in vrouter and in nova.
vrouter takes fqdn hostname from interface where it's placed. 
so for correct work nova should have same name. and this is can't be solved by contrail charms.
