### ISSUE TITLE
[contrail-controller] RabbitMQ has the Web Management console enabled with default credentials

### ISSUE THREAD

**Issue by peppepetra** [Juniper/contrail-charms#135]
Contrail-controller charm Revision 8.
Contrail-controller charm installs RabbitMQ in a docker container. 
An outward facing Web Application, RabbitMQ management portal, was detected, using default
credentials with administrative privileges. Presenting this service increases the threat surface of the
application.

The management console is at 

http://CONTRAIL-CONTROLLER-IP:15673/ 

and default credentials are guest/guest

Password should be at least 10 characters and it must meet at least 3 out of the following 4 complexity rules;
* At least 1 uppercase character (A-Z)
* At least 1 lowercase character (a-z)
* At least 1 digit (0-9)
* At least 1 special character (punctuation) — do not forget to treat space as special
characters too

Or the administrative console should be accessible only on localhost to mitigate the risks.

**Comment by Andrey-mp** [comment]
Is it a charm's bug? It's a general contrail issue from my point of view.

Also user can change the password right after deployment.

**Comment by peppepetra** [comment]
Charm should install the software without presenting security risks. Either set a strong password, disabling the web console or allowing access only on localhost.

**Comment by Andrey-mp** [comment]
how it can help to user if charm will set password that is unknown by user?

**Comment by peppepetra** [comment]
There are several approach to workaround that: writing the password on a file accessible locally on the unit or the charm can implement an action to retrieve that password.
