### ISSUE TITLE
[contrail-controller] Control named service doesn't specify a set of trusted ips to allow recursive queries.

### ISSUE THREAD

**Issue by peppepetra** [Juniper/contrail-charms#137]
Contrail controller charm revision 8.

Contrail controller charm install on a docker container a dns service called contrail-named.
It is possible to query the remote name server for third-party names. If you are probing a remote nameserver, then it allows anyone to use it to resolve third party names (such as www.nessus.org). This allows attackers to perform cache poisoning attacks against this nameserver. If the host allows these recursive queries via UDP, then the host can be used to 'bounce' Denial of Service attacks against another network or system. 

Currently contrail named is configured to allow all the recursive queries:

in /etc/contrail/dns/contrail-named.conf in the control-named container we can find the following:

options {
    directory "/etc/contrail/dns";
    managed-keys-directory "/etc/contrail/dns";
    empty-zones-enable no;
    pid-file "/etc/contrail/dns/contrail-named.pid";
    session-keyfile "/etc/contrail/dns/session.key";
    listen-on port 53 { any; };
    allow-query { any; };
    **allow-recursion { any; };**
    allow-query-cache { any; };
    max-cache-size 32M;
};

Restrict recursive queries to the hosts that should use this nameserver (such as those of the LAN
connected to it). If you are using bind 8, you can do this by using the instruction 'allow-recursion' in the 'options' section of your named.conf. If you are using bind 9, you can define a grouping of internal addresses using the 'acl' command.

**Comment by Andrey-mp** [comment]
container level doesn't allow to modify this config. orchestration level like Juju doesn't have ability to specify something else.
