### ISSUE TITLE
Nrpe check check_contrail_status_agent.py cannot be run as nagios user 

### ISSUE THREAD

**Issue by peppepetra** [Juniper/contrail-charms#138]
After upgrading the contrail charms to revisions noted at the end of the description, we found that all the nrpe check_contrail_status where CRITICAL in nagios.

Investigating the issues, we found that running the same check as sudo user was returning OK,
while running as nagios user (used to run the nrpe check) it was returning nagios user can not preserve the environment.
This was because the updated version of  check_contrail_status_agent.py  was trying to run 
`sudo -E contrail-status`

In order to fix that we had to add to /etc/sudoers.d/nagios SETENV as in the following:

`nagios ALL = NOPASSWD:SETENV: /usr/bin/contrail-status
`

And the checks were OK green again

contrail-analytics  revision 11
contrail-analyticsdb  revision 11
contrail-openstack revision 12
contrail-keystone-auth revision 11
contrail-controller revision 12
contrail-agent revision 12

**Comment by gmeszaros** [comment]
`juju run --application contrail-controller -- 'echo nagios ALL = NOPASSWD:SETENV: /usr/bin/contrail-status | sudo tee /etc/sudoers.d/nagios'`

**Comment by Andrey-mp** [comment]
fixed https://github.com/tungstenfabric/tf-charms/commit/2bcd27255c63f4e1e5bf07643e61c986a504c51a
