### ISSUE TITLE
iptables FORWARD policy is set to DROP by default: containers and KVMs are unreachable

### ISSUE THREAD

**Issue by auria** [Juniper/contrail-charms#143]
> root@control-7:~# docker version
> Client: Docker Engine - Community
>  Version:           19.03.4
>  API version:       1.40
>  Go version:        go1.12.10
>  Git commit:        9013bf583a
>  Built:             Fri Oct 18 15:54:09 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false

### Relevant input

- Relevant code: https://github.com/docker/libnetwork/blob/bump_19.03/drivers/bridge/setup_ip_forwarding.go#L24
- daemon.json sample: https://gist.github.com/melozo/6de91558242fb8ca4212e4a73fbddde6

### Solution
Add a `daemon.json` template to the contrail-controller, contrail-analytics and contrail-analyticsdb charms and a Juju config parameter `docker-iptables` (default: false) to enable/disable such value.

 `/etc/docker/daemon.json` with `{“iptables”: false}`

**Comment by Vultaire** [comment]
Note: commit 25f1ee3 adds a docker-opts config option to many of the charms which should be usable to supply the {"iptables": false} setting

**Comment by Andrey-mp** [comment]
thank you @Vultaire , I forget to close this.
