### ISSUE TITLE
contrail-analytics & contrail-analytics-db dont support no_proxy env setting

### ISSUE THREAD

**Issue by ianj101** [Juniper/contrail-charms#150]
Using a local repo for docker binary install but ignores no_proxy when trying to install gpg key.

Should http & no_proxy be added to _format_curl_https_proxy_opt() function.

[Link](https://github.com/tungstenfabric/tf-charms/blob/master/contrail-analytics/hooks/docker_utils.py#L27-L33)

def _format_curl_https_proxy_opt():
    proxy_settings = env_proxy_settings(['https'])
    https_proxy = None
    if proxy_settings:
        https_proxy = proxy_settings.get('https_proxy')
        return '--proxy {}'.format(https_proxy) if https_proxy else ''
    return ''

**Comment by gmeszaros** [comment]
[fix pushed](https://github.com/tungstenfabric/tf-charms/commit/294bf579e40e600933146b6b5b905bdc9e4788c3)
