### ISSUE TITLE
contrail-agent: agent is not ready. Reason: inactive

### ISSUE THREAD

**Issue by AshleyLai** [Juniper/contrail-charms#151]
Deployed Contrail version 2003.  juju status shows contrail-agent units are in blocked state.

  contrail-agent/0* blocked idle 10.244.48.201 agent is not ready. Reason: inactive

vrouter kernel module is PRESENT
== Contrail vrouter ==
nodemgr: active
agent: inactive

systemctl shows jujud-unit-contrail-agent service is active:
jujud-unit-contrail-agent-0.service loaded active running juju unit agent for contrail-agent/0

Restarted all the docker nodes in contrail-agent did not fix the issue.

**Comment by Andrey-mp** [comment]
fixed https://github.com/tungstenfabric/tf-charms/commit/baa4c580d5935f86a9feca5191a5d3842a5c4b10
