### ISSUE TITLE
Nrpe check fails if ssl_enabled is true (for port 8082)

### ISSUE THREAD

**Issue by gmeszaros** [Juniper/contrail-charms#152]
it is hardcoded in the charm, to only check plain http on port 8082, where it only listens on https if ssl_enabled is set.

https://github.com/tungstenfabric/tf-charms/blob/master/contrail-controller/hooks/contrail_controller_utils.py#L439

should add -S if config["ssl_enabled"] is True

**Comment by gmeszaros** [comment]
```juju run --application contrail-controller -- "sed -i 's/-p 8082/-p 8082 -S/' /etc/nagios/nrpe.d/check_check_contrail_api.cfg"```

**Comment by Andrey-mp** [comment]
fixed https://github.com/tungstenfabric/tf-charms/commit/10e0d1fadda11cecf30dfa430b663d0700988d49
