### ISSUE TITLE
contrail charms fails changing docker credentials

### ISSUE THREAD

**Issue by gmeszaros** [Juniper/contrail-charms#156]
An already working environment, when docker credentials need update (expired on the registry, or got updated), the charm will try indefinitely to pull the docker images with the old password and fail due to the password already being changed on the registry.

Manual workaround to get the issue resolved is to docker logout on each boxes so that the charm will re-login with the new credentials.

**Comment by Andrey-mp** [comment]
https://review.opencontrail.org/c/tungstenfabric/tf-charms/+/59169
