### ISSUE TITLE
Feature REQ:  Add ability to set TRUSTCHK and SPOOFCHK for VF

### ISSUE THREAD

**Issue by derekrobertson** [Juniper/contrail-charms#162]
Please add configuration options to contrail-agent charm to allow setting value of TRUST and SPOOFCHK on the VF interfaces that are created for each SRIOV card.

Currently we need to do this in a startup script:

# Set trust on and spoofcheck off
for i in {0..11}; do ip link set dev <nic1> vf $i trust on spoofchk off; done
for i in {0..11}; do ip link set dev <nic2> vf $i trust on spoofchk off; done
for i in {0..11}; do ip link set dev <nic3> vf $i trust on spoofchk off; done
for i in {0..11}; do ip link set dev <nic4> vf $i trust on spoofchk off; done

**Comment by Andrey-mp** [comment]
please file this issue in official TF jira https://jira.tungsten.io/projects/TC/summary
