### ISSUE TITLE
contrail-ansible issues when deploying Contrail 4.0.2

### ISSUE THREAD

**Issue by bbcmicrocomputer** [Juniper/contrail-charms#2]
When deploying Contrail 4.0.2 with current master branch charms, the following errors are raised when systemd contrail-ansible unit runs inside the contrail-analyticsdb and contrail-controller containers:

contrail-analyticsdb:
```
Jan 25 18:09:57 vm01 systemd[1]: Starting Contrail Analyticsdb configuration...
Jan 25 18:09:58 vm01 contrailctl[29]: Additional properties are not allowed ('opscenter_ip' was unexpected)
Jan 25 18:10:03 vm01 systemd[1]: contrail-ansible.service: Main process exited, code=exited, status=1/FAILURE
Jan 25 18:10:03 vm01 systemd[1]: Failed to start Contrail Analyticsdb configuration.
Jan 25 18:10:05 vm01 systemd[1]: contrail-ansible.service: Unit entered failed state.
Jan 25 18:10:05 vm01 systemd[1]: contrail-ansible.service: Failed with result 'exit-code'.
```
contrail-controller:
```
Jan 26 11:35:17 vm01 systemd[1]: Starting Contrail controller configuration...
Jan 26 11:35:20 vm01 contrailctl[163719]: Additional properties are not allowed ('compute_manager_ip', 'image_manager_ip' were unexpected)
Jan 26 11:35:20 vm01 systemd[1]: contrail-ansible.service: Main process exited, code=exited, status=1/FAILURE
Jan 26 11:35:20 vm01 systemd[1]: Failed to start Contrail controller configuration.
Jan 26 11:35:20 vm01 systemd[1]: contrail-ansible.service: Unit entered failed state.
Jan 26 11:35:20 vm01 systemd[1]: contrail-ansible.service: Failed with result 'exit-code'.
```
Fix:
contrail-analyticsdb - comment out 'opscenter_ip' in /etc/contrailctl/analyticsdb.conf and run 'systemctl restart contrail-ansible'.

contrail-controller - comment out 'compute_manager_ip' and 'image_manager_ip' in /etc/contrailctl/controller.conf and run 'systemctl restart contrail-ansible'.

Ideally the charms would tweak config templates based upon Contrail version.

**Comment by Andrey-mp** [comment]
Please use specific tag for each version.
For 4.0.2 is https://github.com/Juniper/contrail-charms/tree/v4.0.2

**Comment by bbcmicrocomputer** [comment]
Thanks for the info.

Does this mean there will be a different charm per Contrail version?

**Comment by Andrey-mp** [comment]
Good question. I don't have the answer...

I still do not understand should charms be in the charm store or not.
If yes then we must add version detection to charm and generates correct configuration files.
But this question to Rudra or Marketing.

**Comment by bbcmicrocomputer** [comment]
I personally think this is irrelevant of whether the charms are in the Charm Store or not (although I think they very much should be!).
Regardless of where you obtain the charms from, I think a charm version per Contrail release is unsustainable for at least the following reasons:

* The difficulty and confusion in requiring the user to seek and obtain the right version of charms for their Contrail release (this bug report is an example ;) ).
* Will all Contrail charms be versioned the same, even if there's no changes for certain charms between Contrail releases? Differing versions between charms per Contrail release will add to the confusion :) .
* Fixing bugs and adding features (sometimes retro-fitting features). Are you going to add all new bug fixes/features to all charm variants? And the charm variants will continue to grow with releases!
* If the charms support upgrading between Contrail releases, obtaining a new charm version could make upgrades unnecessarily more complicated.

To add some perspective, the official OpenStack charms are one set of charms which support multiple OpenStack releases.

**Comment by Andrey-mp** [comment]
issue in LP - https://bugs.launchpad.net/juniperopenstack/+bug/1746094

**Comment by Andrey-mp** [comment]
done in https://github.com/Juniper/contrail-charms/compare/7ca861b...2db530b
