### ISSUE TITLE
contrail-keystone-auth.conf contains reference to non-existent memcached server

### ISSUE THREAD

**Issue by bbcmicrocomputer** [Juniper/contrail-charms#3]
When deploying current master branch charms, /etc/contrail/contrail-keystone-auth.conf in the controller container contains a reference to a non-existent memcached server.

/etc/contrail/contrail-keystone-auth.conf:
```
[KEYSTONE]
auth_url= http://192.168.122.241:35357/v2.0 
auth_host=192.168.122.241
auth_protocol=http
auth_port=35357
admin_user=admin
admin_password=password
admin_tenant_name=admin
memcache_servers=127.0.0.1:11211
;insecure=False
;certfile=/etc/contrail/ssl/certs/keystone.pem
;keyfile=/etc/contrail/ssl/certs/keystone.pem
;cafile=/etc/contrail/ssl/certs/keystone_ca.pem
```
```
root@vm01(controller):/# netstat -nlp | grep 11211
root@vm01(controller):/# netstat -nlp | grep 8082 
tcp        0      0 0.0.0.0:8082            0.0.0.0:*               LISTEN      242069/python   
root@vm01(controller):/#
```

**Comment by Andrey-mp** [comment]
This issue should be addressed to contrail-ansible-internal repo cause it generates this config file and installed software,
https://github.com/Juniper/contrail-ansible-internal/blob/master/playbooks/roles/contrail/common/templates/contrail-keystone-auth.conf.j2

**Comment by bbcmicrocomputer** [comment]
Can you file the appropriate project bug (and keep this bug open if adjustments will be required afterwards to the charms)?

Thanks!

**Comment by Andrey-mp** [comment]
Hi,
Here is two similar bugs:
https://bugs.launchpad.net/juniperopenstack/+bug/1722392
https://bugs.launchpad.net/juniperopenstack/+bug/1722391

**Comment by bbcmicrocomputer** [comment]
Both those links give me 'Error: Page not found'.

**Comment by Andrey-mp** [comment]
These bugs are in Juniper's private LP...
I made 1722392 as public - try to open it again.

**Comment by Andrey-mp** [comment]
one more review for this topic https://review.opencontrail.org/#/c/36764/
