### ISSUE TITLE
No current support for proxy configs

### ISSUE THREAD

**Issue by phvalguima** [Juniper/contrail-charms#44]
According to: https://docs.docker.com/config/daemon/systemd/, whenever docker is working behind a proxy, you need to create a file on /etc/systemd/system/docker.service.d/http-proxy.conf with proxy values. 
This is not the case at the moment for the charms. So, the solution would be to add new options on the charm to manually configure proxy.

**Comment by Andrey-mp** [comment]
it's not supported for master branch that is actually for R4.x version.
But it's supported for R5 branch - https://github.com/Juniper/contrail-charms/blob/R5/contrail-analytics/config.yaml#L37-L57
