### ISSUE TITLE
Contrail fails due to missing NTP service on Ubuntu

### ISSUE THREAD

**Issue by phvalguima** [Juniper/contrail-charms#45]
Contrail charms mark that there is no NTP service and therefore they are unsynchronized. Looking into Juniper/Contrail docs, I can find this reference: https://www.juniper.net/documentation/en_US/contrail5.0/information-products/pathway-pages/getting-started-pwp.html

The discussion indicates ntpq is the tool of choice for Contrail services, which does not come installed by default on Ubuntu. If ntpq is a prerequisite for Contrail services to work, than the charms should handle its installation and configuration.

My suggestion is to have extra config files to add entries to /etc/ntp.conf like "server SERVER_IP iburst"

**Comment by Andrey-mp** [comment]
Hi, can you please specify versions of charms and containers?
Some fix was added two months ago in contrail. but it can be unreleased yet.
this message comes to charms from contrail-status. contrail-status takes it from status of nodemgr. nodemgr checks is time synced from ntp or chrony services depending on what installed on host.
previously only ntp was supported.
