### ISSUE TITLE
Cannot choose which IP to use for BGP session on multi-nic host

### ISSUE THREAD

**Issue by phvalguima** [Juniper/contrail-charms#46]
Contrail-controller is the one responsible for setting up BGP sessions wth (v)MX and the charm does not allow me to choose which IP in my host I want to use if I have multiple options. The only way to force contrail-controller to do that is on post-deployment, where I manually override "hostips" on entrypoint.sh and reboot the container with "docker restart".

I believe a much cleaner way would be to set hostips as a env variable and pass that as a parameter on run method at: https://github.com/Juniper/contrail-charms/blob/R5/contrail-controller/hooks/docker_utils.py#L144

The new run method at docker_utils would look like similar to:

def run(image, tag, volumes, remove=False):
    image_id = get_image_id(image, tag)
    args = [DOCKER_CLI, "run"]
    if remove:
        args.append("--rm")
    args.extend(["-i", "--network", "host"])
    for volume in volumes:
        args.extend(["-v", volume])
    args.extend([image_id])
    bgp_ip = _check_for_bgpip_format( config('bgp_host_ip') )
    if bgp_ip is not None:
        args.extend(["--env", "HOST_IP={}".format( bgp_ip )])
    check_call(args)

_check_for_bgpip_format would be a method that receives IP in string format and check if that is valid. Returns valid IP as string or None otherwise.
Then, you need to set bgp_host_ip on config.yaml, preferably setting as "" by default.

You'll also need to do a tweak at control's entrypoint.sh. You'd need to check if HOST_IP env variable exists, otherwise proceed as you are doing at the moment.

**Comment by Andrey-mp** [comment]
Can you please tell me exact scenario? 
I didn't understand what controller should do and how. Where the HOST_IP should be used inside entrypoint.sh and how?

contrail-controller charm has config option control-network that allows to specify network to listen on.

**Comment by Andrey-mp** [comment]
There is no response. Close it for now.
