### ISSUE TITLE
/etc/hosts entries are not persistent across reboots

### ISSUE THREAD

**Issue by phausman** [Juniper/contrail-charms#60]
Pull request [#51](https://github.com/Juniper/contrail-charms/pull/51) "Allow using /etc/hosts for RabbitMQ name resolution" introduces new entries in ``/etc/hosts``. Those entries are not persistent across reboots on hosts deployed by juju. 

By default, juju sets cloud-init configuration option 'manage_etc_hosts: true' [1]. As described in cloud-init code [2], "If set to ``true`` or ``template``, cloud-init will generate ``/etc/hosts`` using the template located in ``/etc/cloud/templates/hosts.tmpl``."

Since ``/etc/cloud/templates/hosts.tmpl`` is not updated with new entries, they won't show up in ``/etc/hosts`` after the reboot.

1. https://bugs.launchpad.net/ubuntu/+source/juju-core/+bug/1475260
2. https://github.com/cloud-init/cloud-init/blob/ubuntu/bionic/cloudinit/config/cc_update_etc_hosts.py#L19-L22

**Comment by Andrey-mp** [comment]
i have juju 2.4.3 installed and i don't see manage_etc_hosts in my cloud init config.

**Comment by Andrey-mp** [comment]
@phausman can you please tell me your version of juju?
I would suggest to remove or switch off cloud-init at all. or at least switch off managing of /etc/hosts.
It would be than patching hosts template from my point of view.

**Comment by n-pochet** [comment]
@Andrey-mp 
We are running juju 2.6.X.
We cannot switch off cloud-init as juju is relying on that.

**Comment by Andrey-mp** [comment]
@n-pochet so, you are OK if I just add updating of hosts.debian.tmpl with the same entries as in /etc/hosts?

**Comment by n-pochet** [comment]
@Andrey-mp That sounds OK to me.

**Comment by Andrey-mp** [comment]
please check - https://github.com/Juniper/contrail-charms/commit/e0ce7b361851b573afe4449f158e67a8f05b7fc3
