### ISSUE TITLE
admin password changes are not propagated

### ISSUE THREAD

**Issue by aieri** [Juniper/contrail-charms#61]
After changing the admin password via the openstack api, `/etc/contrail/common_config.env` is not updated with the new password.
As a consequence, the contrail api fails to authenticate against keystone.

**Comment by Andrey-mp** [comment]
HI @aieri 
It's not bug for Juju. admin password was set by charm-keystone and contrails' charms can take only from there by relation.
If password is changed via OpenStack API - charms can't get it,

**Comment by aieri** [comment]
that's right, of course!
