### ISSUE TITLE
'submit a bug' link in the charmstore page is broken

### ISSUE THREAD

**Issue by aieri** [Juniper/contrail-charms#63]
The 'submit a bug' link points to a non-existent launchpad project, but if bugs are to be tracked here, its destination should be updated.

**Comment by aieri** [comment]
After the move of jujucharms.com to jaas.ai the 'submit a bug' link has completely disappeared. A link pointing to this repo should be provided, otherwise users won't know where to file bugs.

**Comment by Andrey-mp** [comment]
link is there.
but ideally opensource users should file bugs via TF Jira (this work is on going) and private customer should escalate issues to Juniper's field engineer.
