### ISSUE TITLE
Apparmor support

### ISSUE THREAD

**Issue by aieri** [Juniper/contrail-charms#64]
When running contrail-agents with apparmor set to 'enforce', nova-compute is unable to operate on `/dev/net/tun` and virtual interfaces cannot then be created.

```
kernel: [192532.931054] audit: type=1400 audit(1555595396.066:96): apparmor="DENIED" operation="open" profile="/usr/bin/nova-compute" name="/dev/net/tun" pid=52870 comm="ip" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=0
kernel: [192533.045118] audit: type=1400 audit(1555595396.182:97): apparmor="DENIED" operation="open" profile="/usr/bin/nova-compute" name="/dev/net/tun" pid=52874 comm="tunctl" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=0
```

In traditional neutron-based setups the above is apparently not necessary, therefore the nova-compute charm does not ship with an apparmor profile that allows such behavior.
I believe the contrail-agent should add further apparmor rules so that apparmor can be enabled in a contrail environment.

**Comment by dshcherb** [comment]
I think this should be addressed here https://bugs.launchpad.net/charm-nova-compute/+bug/1841111 https://review.opendev.org/678108 as contrail charms will not be able to override the profile for nova-compute.

The code that tries to access /dev/net/tun is present in nova itself so it makes sense to have that profile change done in charm-nova-compute.

**Comment by Andrey-mp** [comment]
Thank you @dshcherb !
