### ISSUE TITLE
Web UI reports multiple alarms upon first login

### ISSUE THREAD

**Issue by bbcmicrocomputer** [Juniper/contrail-charms#7]
Deploying Contrail 4.1 using master branch charms with the attached bundle - [contrail-docker-bundle-ha-ocata.yaml.txt](https://github.com/Juniper/contrail-charms/files/1792579/contrail-docker-bundle-ha-ocata.yaml.txt).

Upon first login to Web UI you're presented with multiple alarms, as shown in the screenshots below:

![screenshot from 2018-03-08 10-13-29](https://user-images.githubusercontent.com/6774503/37144427-4e84d9ec-22be-11e8-958b-30aa041a744d.png)
![screenshot from 2018-03-08 10-14-08](https://user-images.githubusercontent.com/6774503/37144434-5317e594-22be-11e8-8eae-86b509522bdf.png)

You can acknowledge these alarms and they don't appear again.

I suspect these alarms arise during starting of services when perhaps charm relations aren't complete. If that is the case then we should automatically acknowledge (or delete) those false alarms.

**Comment by Andrey-mp** [comment]
Hi Robert,

Most alarms should disappear when service is come up.
But some of this can't due to bugs in Contrail internal code - https://bugs.launchpad.net/juniperopenstack/+bug/1694048

**Comment by bbcmicrocomputer** [comment]
Can you make this bug public? (Error: Page not found)

**Comment by Andrey-mp** [comment]
Done

**Comment by Andrey-mp** [comment]
added to known issues https://github.com/Juniper/contrail-charms/tree/R4#known-issues
