### ISSUE TITLE
contrail-openstack charm does not make sure haproxy is installed for lbaasv2 support

### ISSUE THREAD

**Issue by dshcherb** [Juniper/contrail-charms#71]
Looking at the doc below I can see that it is a requirement to have haproxy installed on compute nodes in order to get haproxy instances spawned in lbaas network namespaces.

https://www.juniper.net/documentation/en_US/contrail5.1/topics/task/configuration/load-balance-as-service-vnc.html#id-contrail-lbaas-implementation
"To use the LBaaS feature, HAProxy, version 1.5 or greater and iproute2, version 3.10.0 or greater must both be installed on the Contrail compute nodes."

Looking at the charm code (and at installed packages in a lab env) I do not see any code in contrail-openstack to check for the haproxy package presence or its installation:
 
```
➜  contrail-openstack git:(R5) ✗ grep -RiP haproxy ; echo $?
1

```
There is some code to enable the lbaas extension:

```
➜  contrail-openstack git:(R5) ✗ grep -RiP lbaas
hooks/contrail_openstack_hooks.py:        "/usr/lib/python2.7/dist-packages/neutron_lbaas/extensions"]

```
```
    service_plugins = base + ".loadbalancer.v2.plugin.LoadBalancerPluginV2"
    extensions = [
        "/usr/lib/python2.7/dist-packages/neutron_plugin_contrail/extensions",
        "/usr/lib/python2.7/dist-packages/neutron_lbaas/extensions"]

```

Another reference besides docs is the contrail fabric utilities which has some code to install haproxy:
https://github.com/Juniper/contrail-fabric-utils/blob/8fa5b856b8150fb3cb6fc0c9a6894730a79daca2/fabfile/utils/install.py#L85-L87

**Comment by Andrey-mp** [comment]
Hi Dmitry,
in containers deploy haproxy is not needed on compute host. it's present inside contrail-vrouter-agent container.

**Comment by dshcherb** [comment]
@Andrey-mp Thanks, this makes sense. Looks like this doc entry has not been updated.
