### ISSUE TITLE
contrail-controller: hook failed: "http-services-relation-joined"

### ISSUE THREAD

**Issue by AshleyLai** [Juniper/contrail-charms#74]
During Contrail deployment contrail-controller failed with the following error.

contrail-controller/0         error        idle        21        10.244.35.3                         hook failed: "http-services-relation-joined"

2019-06-14 04:08:45 DEBUG http-services-relation-joined   File "/var/lib/juju/agents/unit-contrail-controller-2/charm/hooks/http-services-relation-joined", line 596, in <module>
2019-06-14 04:08:45 DEBUG http-services-relation-joined     main()
2019-06-14 04:08:45 DEBUG http-services-relation-joined   File "/var/lib/juju/agents/unit-contrail-controller-2/charm/hooks/http-services-relation-joined", line 590, in main
2019-06-14 04:08:45 DEBUG http-services-relation-joined     hooks.execute(sys.argv)
2019-06-14 04:08:45 DEBUG http-services-relation-joined   File "/var/lib/juju/agents/unit-contrail-controller-2/charm/hooks/charmhelpers/core/hookenv.py", line 914, in execute
2019-06-14 04:08:45 DEBUG http-services-relation-joined     self._hooks[hook_name]()
2019-06-14 04:08:45 DEBUG http-services-relation-joined   File "/var/lib/juju/agents/unit-contrail-controller-2/charm/hooks/http-services-relation-joined", line 404, in http_services_joined
2019-06-14 04:08:45 DEBUG http-services-relation-joined     services=yaml.dump(_http_services(str(vip))))
2019-06-14 04:08:45 DEBUG http-services-relation-joined   File "/var/lib/juju/agents/unit-contrail-controller-2/charm/hooks/http-services-relation-joined", line 384, in _http_services
2019-06-14 04:08:45 DEBUG http-services-relation-joined     "cookie " + addr + " weight 1 maxconn 1024 check port 8080"]]},
2019-06-14 04:08:45 DEBUG http-services-relation-joined TypeError: cannot concatenate 'str' and 'NoneType' objects
2019-06-14 04:08:45 ERROR juju.worker.uniter.operation runhook.go:132 hook "http-services-relation-joined" failed: exit status 1

**Comment by Andrey-mp** [comment]
1. please provide options from bundle that are related to controller and haproxy.
2. is it one such error in log or log has several such traces?
3. from the code I see that it can't obtain own ip - https://github.com/Juniper/contrail-charms/blob/R5/contrail-controller/hooks/common_utils.py#L32
can you please paste here output of `juju status`, `ip addr`, `ip route`, `ip link`?

**Comment by AshleyLai** [comment]
Hi Andrey - please find the bundle attached.  Noted that I renamed .yaml to .txt as it does not allow to attach .yaml file.  This bundle is also used for issue #72 and #73.
[bundle.txt](https://github.com/Juniper/contrail-charms/files/3296478/bundle.txt)

contrail-controller/0         error        idle       21        10.244.35.3                         hook failed: "http-services-relation-joined"
  bcache-tuning/6             active       idle                 10.244.35.3                         bcache devices tuned
  canonical-livepatch/18      active       idle                 10.244.35.3                         Running kernel 4.15.0-51.55-generic, patchState: nothing-to-apply
  nrpe-host/22                active       idle                 10.244.35.3                         ready
  ntp-lp1817516/4             active       idle                 10.244.35.3     123/udp             ntp: Ready
contrail-controller/1         error        idle       22        10.244.35.1                         hook failed: "http-services-relation-joined"
  bcache-tuning/5             active       idle                 10.244.35.1                         bcache devices tuned
  canonical-livepatch/17      active       idle                 10.244.35.1                         Running kernel 4.15.0-51.55-generic, patchState: nothing-to-apply
  nrpe-host/21                active       idle                 10.244.35.1                         ready
  ntp-lp1817516/3             active       idle                 10.244.35.1     123/udp             ntp: Ready
contrail-controller/2*        error        idle       23        10.244.34.255                       hook failed: "http-services-relation-joined"
  bcache-tuning/2*            active       idle                 10.244.34.255                       bcache devices tuned
  canonical-livepatch/16      active       idle                 10.244.34.255                       Running kernel 4.15.0-51.55-generic, patchState: nothing-to-apply
  nrpe-host/18                active       idle                 10.244.34.255                       ready

Below is the output from contrail-controller/2 node:
ubuntu@aristos:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br-eth0 state UP group default qlen 1000
    link/ether 2c:59:e5:3a:cf:78 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000
    link/ether 2c:59:e5:3a:cf:79 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::2e59:e5ff:fe3a:cf79/64 scope link 
       valid_lft forever preferred_lft forever
4: eno3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 2c:59:e5:3a:cf:7a brd ff:ff:ff:ff:ff:ff
5: eno4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 2c:59:e5:3a:cf:7b brd ff:ff:ff:ff:ff:ff
6: eth1.2746@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue master br-eth1-2746 state UP group default qlen 1000
    link/ether 2c:59:e5:3a:cf:79 brd ff:ff:ff:ff:ff:ff
7: eth1.2734@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
    link/ether 2c:59:e5:3a:cf:79 brd ff:ff:ff:ff:ff:ff
    inet 10.244.34.255/21 brd 10.244.39.255 scope global eth1.2734
       valid_lft forever preferred_lft forever
    inet6 fe80::2e59:e5ff:fe3a:cf79/64 scope link 
       valid_lft forever preferred_lft forever
8: eth1.2748@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
    link/ether 2c:59:e5:3a:cf:79 brd ff:ff:ff:ff:ff:ff
    inet 192.168.35.6/26 brd 192.168.35.63 scope global eth1.2748
       valid_lft forever preferred_lft forever
    inet6 fe80::2e59:e5ff:fe3a:cf79/64 scope link 
       valid_lft forever preferred_lft forever
9: eth1.2747@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
    link/ether 2c:59:e5:3a:cf:79 brd ff:ff:ff:ff:ff:ff
    inet 192.168.36.6/26 brd 192.168.36.63 scope global eth1.2747
       valid_lft forever preferred_lft forever
    inet6 fe80::2e59:e5ff:fe3a:cf79/64 scope link 
       valid_lft forever preferred_lft forever
10: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:35:f0:05 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
11: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN group default qlen 1000
    link/ether 52:54:00:35:f0:05 brd ff:ff:ff:ff:ff:ff
12: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:17:40:a3:e7 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
13: lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 5e:36:b8:cd:ff:cf brd ff:ff:ff:ff:ff:ff
    inet 10.156.240.1/24 scope global lxdbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::5c36:b8ff:fecd:ffcf/64 scope link 
       valid_lft forever preferred_lft forever
14: br-eth1-2746: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
    link/ether fa:c9:92:50:3e:69 brd ff:ff:ff:ff:ff:ff
    inet 192.168.33.21/24 brd 192.168.33.255 scope global br-eth1-2746
       valid_lft forever preferred_lft forever
    inet6 fe80::f8c9:92ff:fe50:3e69/64 scope link 
       valid_lft forever preferred_lft forever
15: br-eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 26:56:f6:88:8b:11 brd ff:ff:ff:ff:ff:ff
    inet 10.244.49.34/21 brd 10.244.55.255 scope global br-eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::2456:f6ff:fe88:8b11/64 scope link 
       valid_lft forever preferred_lft forever
16: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br-eth0 state UNKNOWN group default qlen 1000
    link/ether fe:16:3e:09:c2:dd brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc16:3eff:fe09:c2dd/64 scope link 
       valid_lft forever preferred_lft forever
17: vnet1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br-eth0 state UNKNOWN group default qlen 1000
    link/ether fe:16:3e:85:99:31 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc16:3eff:fe85:9931/64 scope link 
       valid_lft forever preferred_lft forever
18: vnet2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br-eth0 state UNKNOWN group default qlen 1000
    link/ether fe:16:3e:5a:b8:1d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc16:3eff:fe5a:b81d/64 scope link 
       valid_lft forever preferred_lft forever
19: vnet3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br-eth0 state UNKNOWN group default qlen 1000
    link/ether fe:16:3e:e9:1f:56 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc16:3eff:fee9:1f56/64 scope link 
       valid_lft forever preferred_lft forever
20: vnet4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc fq_codel master br-eth1-2746 state UNKNOWN group default qlen 1000
    link/ether fe:16:3e:ad:78:4b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc16:3eff:fead:784b/64 scope link 
       valid_lft forever preferred_lft forever
22: vethJXW974@if21: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-eth0 state UP group default qlen 1000
    link/ether fe:d0:dd:7e:8e:ca brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::fcd0:ddff:fe7e:8eca/64 scope link 
       valid_lft forever preferred_lft forever
24: vethUNXMJG@if23: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue master br-eth1-2746 state UP group default qlen 1000
    link/ether fe:a4:53:fd:7e:d4 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::fca4:53ff:fefd:7ed4/64 scope link 
       valid_lft forever preferred_lft forever
ubuntu@aristos:~$ ip route
default via 10.244.48.1 dev br-eth0 proto static 
10.156.240.0/24 dev lxdbr0 proto kernel scope link src 10.156.240.1 
10.244.32.0/21 dev eth1.2734 proto kernel scope link src 10.244.34.255 
10.244.48.0/21 dev br-eth0 proto kernel scope link src 10.244.49.34 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.33.0/24 dev br-eth1-2746 proto kernel scope link src 192.168.33.21 
192.168.35.0/26 dev eth1.2748 proto kernel scope link src 192.168.35.6 
192.168.36.0/26 dev eth1.2747 proto kernel scope link src 192.168.36.6 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown 
ubuntu@aristos:~$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br-eth0 state UP mode DEFAULT group default qlen 1000
    link/ether 2c:59:e5:3a:cf:78 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 2c:59:e5:3a:cf:79 brd ff:ff:ff:ff:ff:ff
4: eno3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 2c:59:e5:3a:cf:7a brd ff:ff:ff:ff:ff:ff
5: eno4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 2c:59:e5:3a:cf:7b brd ff:ff:ff:ff:ff:ff
6: eth1.2746@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue master br-eth1-2746 state UP mode DEFAULT group default qlen 1000
    link/ether 2c:59:e5:3a:cf:79 brd ff:ff:ff:ff:ff:ff
7: eth1.2734@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 2c:59:e5:3a:cf:79 brd ff:ff:ff:ff:ff:ff
8: eth1.2748@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 2c:59:e5:3a:cf:79 brd ff:ff:ff:ff:ff:ff
9: eth1.2747@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 2c:59:e5:3a:cf:79 brd ff:ff:ff:ff:ff:ff
10: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 52:54:00:35:f0:05 brd ff:ff:ff:ff:ff:ff
11: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN mode DEFAULT group default qlen 1000
    link/ether 52:54:00:35:f0:05 brd ff:ff:ff:ff:ff:ff
12: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:17:40:a3:e7 brd ff:ff:ff:ff:ff:ff
13: lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 5e:36:b8:cd:ff:cf brd ff:ff:ff:ff:ff:ff
14: br-eth1-2746: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether fa:c9:92:50:3e:69 brd ff:ff:ff:ff:ff:ff
15: br-eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 26:56:f6:88:8b:11 brd ff:ff:ff:ff:ff:ff
16: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br-eth0 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:09:c2:dd brd ff:ff:ff:ff:ff:ff
17: vnet1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br-eth0 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:85:99:31 brd ff:ff:ff:ff:ff:ff
18: vnet2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br-eth0 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:5a:b8:1d brd ff:ff:ff:ff:ff:ff
19: vnet3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br-eth0 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:e9:1f:56 brd ff:ff:ff:ff:ff:ff
20: vnet4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc fq_codel master br-eth1-2746 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:ad:78:4b brd ff:ff:ff:ff:ff:ff
22: vethJXW974@if21: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-eth0 state UP mode DEFAULT group default qlen 1000
    link/ether fe:d0:dd:7e:8e:ca brd ff:ff:ff:ff:ff:ff link-netnsid 0
24: vethUNXMJG@if23: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue master br-eth1-2746 state UP mode DEFAULT group default qlen 1000
    link/ether fe:a4:53:fd:7e:d4 brd ff:ff:ff:ff:ff:ff link-netnsid 0
ubuntu@aristos:~$

**Comment by Andrey-mp** [comment]
Hi Ashley, 
you have network setting in bundle: contrail-control-net: &contrail-control-net "192.168.33.64/26 192.168.33.128/26 192.168.33.192/26"
but real network is `inet 192.168.33.21/24`
so the common code from charmhelpers couldn't find the proper IP.
I can try to change our code to get IP from default iface (default via 10.244.48.1 dev br-eth0 proto static) but it will be different that user wants and user will not know about the different behaviour.
second solution is to write more deterministic error.

**Comment by AshleyLai** [comment]
Hi Andrey,

Thanks for looking.  Having a more details error is always helpful.  I will change the contrail control network.

**Comment by AshleyLai** [comment]
Andrey,

The control-network option in config.yaml file description says "If not specified, default network will be used.".  For testing it can use the 10.244.48.1 network but how does it know what range of unused IP to use?  We can reserve a range of IPs on the 10.244.48.1 network to use for this.

**Comment by Andrey-mp** [comment]
Ashley,
It will detect default route for the machine and use CIDR of interface from the default route.
Also this interface will be used to obtain own IP to listen.
