### ISSUE TITLE
Flow Series in Web UI shows no results

### ISSUE THREAD

**Issue by bbcmicrocomputer** [Juniper/contrail-charms#8]
Deploying Contrail 4.1 using master branch charms with the attached bundle - 
[contrail-docker-bundle-ha-ocata.yaml.txt](https://github.com/Juniper/contrail-charms/files/1792634/contrail-docker-bundle-ha-ocata.yaml.txt).

I've launched a new OpenStack instance (10.0.5.3), ssh'ed into it, left ping running against the local 10.0.5.1 gateway, yet Flow Series within the Web UI shows no results, as shown in the screenshots below:

![screenshot from 2018-03-08 10-15-29](https://user-images.githubusercontent.com/6774503/37145053-28ae260e-22c0-11e8-9b12-65d5d93504f9.png)
![screenshot from 2018-03-08 10-15-16](https://user-images.githubusercontent.com/6774503/37145072-349b672e-22c0-11e8-92f9-f2eca676e224.png)

Running 'flow' on the compute host of the instance I see results:

```
root@vm04:~# flow -l
Flow table(size 80609280, entries 629760)

Entries: Created 584 Added 584 Deleted 1098 Changed 1098 Processed 584 Used Overflow entries 0
(Created Flows/CPU: 370 214)(oflows 0)

Action:F=Forward, D=Drop N=NAT(S=SNAT, D=DNAT, Ps=SPAT, Pd=DPAT, L=Link Local Port)
 Other:K(nh)=Key_Nexthop, S(nh)=RPF_Nexthop
 Flags:E=Evicted, Ec=Evict Candidate, N=New Flow, M=Modified Dm=Delete Marked
TCP(r=reverse):S=SYN, F=FIN, R=RST, C=HalfClose, E=Established, D=Dead

    Index                Source:Port/Destination:Port                      Proto(V)
-----------------------------------------------------------------------------------
   208164<=>229340       10.0.5.1:1489                                       1 (2)
                         10.0.5.3:0
(Gen: 1, K(nh):35, Action:F, Flags:, QOS:-1, S(nh):12,  Stats:0/0,  SPort 50434,
 TTL 0, Sinfo 0.0.0.0)

   229340<=>208164       10.0.5.3:1489                                       1 (2)
                         10.0.5.1:0
(Gen: 1, K(nh):35, Action:F, Flags:, QOS:-1, S(nh):35,  Stats:149304/14631792,
 SPort 50336, TTL 0, Sinfo 3.0.0.0)

   443396<=>462224       192.168.122.38:50734                                6 (0->2)
                         169.254.0.3:22
(Gen: 1, K(nh):5, Action:N(SD), Flags:, TCP:SSrEEr, QOS:-1, S(nh):9,  Stats:167481/8720133,
 SPort 50837, TTL 0, Sinfo 0.0.0.0)

   462224<=>443396       10.0.5.3:22                                         6 (2->0)
                         10.0.5.2:50734
(Gen: 1, K(nh):35, Action:N(SD), Flags:, TCP:SSrEEr, QOS:-1, S(nh):35,
 Stats:167528/26596625,  SPort 50673, TTL 0, Sinfo 3.0.0.0)
```

I feel like something is misconfigured.

**Comment by Andrey-mp** [comment]
same result as in issue #5 ( https://bugs.launchpad.net/juniperopenstack/+bug/1746719 )

{ [Error: All host(s) tried for query failed. First host tried, 172.31.6.6:9042: AuthenticationError: Authentication provider not set. See innerErrors.]
  innerErrors: 
   { '172.31.6.6:9042': 
      { [AuthenticationError: Authentication provider not set]
        name: 'AuthenticationError',
        stack: 'Error: Authentication provider not set\n    at AuthenticationError.DriverError (/usr/lib64/node_modules/cassandra-driver/lib/errors.js:14:19)\n    at new AuthenticationError (/usr/lib64/node_modules/cassandra-driver/lib/errors.js:76:30)\n    at Connection.startAuthenticating (/usr/lib64/node_modules/cassandra-driver/lib/connection.js:268:21)\n    at responseCallback (/usr/lib64/node_modules/cassandra-driver/lib/connection.js:171:19)\n    at Connection.invokeCallback (/usr/lib64/node_modules/cassandra-driver/lib/connection.js:581:5)\n    at Connection.handleResult (/usr/lib64/node_modules/cassandra-driver/lib/connection.js:519:8)\n    at ResultEmitter.emit (events.js:106:17)\n    at ResultEmitter.each (/usr/lib64/node_modules/cassandra-driver/lib/streams.js:499:15)\n    at ResultEmitter._write (/usr/lib64/node_modules/cassandra-driver/lib/streams.js:464:10)\n    at doWrite (_stream_writable.js:226:10)',
        message: 'Authentication provider not set',
        info: 'Represents an authentication error from the driver or from a Cassandra node.' } },
  info: 'Represents an error when a query cannot be performed because no host is available or could be reached by the driver.',
  message: 'All host(s) tried for query failed. First host tried, 172.31.6.6:9042: AuthenticationError: Authentication provider not set. See innerErrors.' }

**Comment by Andrey-mp** [comment]
it works with latest internal build of 4.1.1 but doesn't find any records (may be the same problem as in issue  about logs query)

**Comment by Andrey-mp** [comment]
https://bugs.launchpad.net/juniperopenstack/+bug/1754863

**Comment by Andrey-mp** [comment]
It happened due to flow-export-rate was 0 by default in the deployment.
I've added flow-export-rate to controller-charm's config and set it to 10 by default.
