### ISSUE TITLE
contrail-agent kernel not supported vrouter

### ISSUE THREAD

**Issue by AshleyLai** [Juniper/contrail-charms#85]
$ sudo contrail-status
Pod      Service  Original Name           State       Id            Status                           
vrouter  agent    contrail-vrouter-agent  restarting  b892df54d769  Restarting (134) 55 seconds ago  
vrouter  nodemgr  contrail-nodemgr        running     ffd682536781  Up 19 minutes                    

vrouter kernel module is PRESENT
== Contrail vrouter ==
nodemgr: active
agent: inactive

=================
$ sudo docker logs b892df54d769
...
INFO: Kernel version does not support vrouter to vrouter encryption - Not adding decrypt0 to vrouter
Config file </etc/contrail/contrail-vrouter-agent.conf> parsing completed.
contrail-vrouter-agent: controller/src/vnsw/agent/vrouter/ksync/ksync_memory.cc:107: void KSyncMemory::Mmap(bool): Assertion `0' failed.
/entrypoint.sh: line 398: 1879970 Aborted                 (core dumped) $@

Is there a special kernel we should be using?
$ uname -a
Linux arnolt 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Andrey-mp** [comment]
Such error we saw when free memory is low on host.

**Comment by AshleyLai** [comment]
Thanks Andrey.  I can redeploy with higher memory constraints.

**Comment by AshleyLai** [comment]
This issue does not exist on baremetals.
