### ISSUE TITLE
contrail-controller api is not ready: keystone connection down

### ISSUE THREAD

**Issue by AshleyLai** [Juniper/contrail-charms#86]
contrail-controller api is not in ready state during bundle deployment.  Please see reason messages below.  The workaround was to restart configapi_api_1.

contrail-controller/0             waiting      idle       18         10.244.49.66                                             api is not ready. Reason: (Generic Connection:Keystone[] connection down)
contrail-controller/1*            waiting      idle       19         10.244.49.53                                             api is not ready. Reason: (Generic Connection:Keystone[Error: An unexpected error prevented the server from fulfilling your request. (HTTP 500) (Request-ID: req-c267e248-6e5a-4599-abf5-657ca7dbd264) at UTC 2019-07-10 23:59:27.985450] connection down)
contrail-controller/2             waiting      executing  20         10.244.49.65                                             (juju-run) api is not ready. Reason: (Generic Connection:Keystone[Error: An unexpected error prevented the server from fulfilling your request. (HTTP 500) (Request-ID: req-d65ecf57-15fc-44e8-883d-0a25be51ae9b) at UTC 2019-07-11 00:01:52.759035] connection down)

**Comment by Andrey-mp** [comment]
looks like that keystone code is broken again in config-api.

**Comment by Andrey-mp** [comment]
fixed in contrail's code.
