### ISSUE TITLE
HTTP Security headers were not identified

### ISSUE THREAD

**Issue by xavpaice** [Juniper/contrail-charms#89]
Regarding the contrail-controller url:

The following HTTP Security headers were not identified during a security scan and could be enabled to further increase security:
• Cacheable HTTPS Response - Unless directed otherwise, browsers may store a local cached
copy of content received from web servers. Some browsers, including Internet Explorer, cache
content accessed via HTTPS. If sensitive information in application responses is stored in the
local cache, then this may be retrieved by other users who have access to the same computer
at a future time.

RECOMMENDATION:
Applications should return caching directives instructing browsers not to store local copies of any sensitive data. The Web Server should return the following header:
Cache-control: no-store
Pragma: no-cache

**Comment by Andrey-mp** [comment]
is it for config API endpoint or for WebUI?

**Comment by Andrey-mp** [comment]
anyway this bug is not for charms. this bug for contrail itself and should be filed in different place.
