### ISSUE TITLE
Log query in Web UI shows no results

### ISSUE THREAD

**Issue by bbcmicrocomputer** [Juniper/contrail-charms#9]
Deploying Contrail 4.1 using master branch charms with the attached bundle - 
[contrail-docker-bundle-ha-ocata.yaml.txt](https://github.com/Juniper/contrail-charms/files/1792677/contrail-docker-bundle-ha-ocata.yaml.txt).

Running a log query for debug messages within the Web UI shows no results, as shown in the screenshot below:

![screenshot from 2018-03-08 10-16-10](https://user-images.githubusercontent.com/6774503/37145704-daf9bc5a-22c1-11e8-8fa0-1d325562bd12.png)

Contrail 3.x used to show lots of debug messages with the equivalent query so I feel something is misconfigured. Probably related to #8 .

**Comment by Andrey-mp** [comment]
https://bugs.launchpad.net/juniperopenstack/+bug/1754860

**Comment by Andrey-mp** [comment]
this is default behavior now - https://github.com/Juniper/contrail-specs/blob/master/analytics-constrained.md
